### ISSUE TITLE
Puppet::Parser::AST::Resource failed

### ISSUE THREAD

**Issue by kirs** [evolvingweb/puppet-apt#8]
I've added `apt::ppa { "ppa:nginx/stable": }` to my site.pp, but there is an error: 
`Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type apt::ppa at /etc/puppet/manifests/site.pp:9`

**Comment by schnablek** [comment]
This sounds like the module is not correctly installed.  Where did you extract the module ZIP to?  Should be /etc/puppet/modules/apt/.

**Comment by kirs** [comment]
Oh, really. Sorry for opening this issue.

**Comment by schnablek** [comment]
No problem, did you get everything working?

**Comment by kirs** [comment]
Yep!

**Comment by schnablek** [comment]
Awesome!
